Repository primus-teoSprint/primus_FE, pull requests merged in 2024-05, with the labels that each got.

#2 [#1] 기초 세팅
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  .swcrc
  README.md
  next.config.mjs
  package-lock.json
  package.json
  src/apis/tool.ts
  src/app/layout.tsx
  src/app/list/.gitkeep
  src/app/mypage/.gitkeep
  src/app/page.tsx
  src/app/search/.gitkeep
  src/app/signin/.gitkeep
  src/app/toolDetail/.gitkeep
  src/app/verification/.gitkeep
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/components/Layout.tsx
  src/components/common/button/.gitkeep
  src/components/common/checkbox/.gitkeep
  src/components/common/mypage/card/.gitkeep
  src/components/common/nav/.gitkeep
  src/components/providers/ReactQueryProviders.tsx
  src/components/providers/index.tsx
  src/constants/api.ts
  src/constants/meta.ts
  src/hooks/.gitkeep
  src/libs/api.ts
  src/mocks/.gitkeep
  src/store/.gitkeep
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/styled.d.ts
  src/utils/.gitkeep
  tsconfig.json
Labels: env, feat

#8 [#7] msw 설정
  README.md
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/apis/tool.ts
  src/components/providers/MswComponent.tsx
  src/components/providers/index.tsx
  src/constants/api.ts
  src/libs/api.ts
  src/mocks/.gitkeep
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/http.ts
  src/mocks/server.ts
  tsconfig.json
Labels: feat

#11 [#4] button 공통 컴포넌트
  package-lock.json
  package.json
  src/components/common/button/.gitkeep
  src/components/common/button/AddButton.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/SplitButton.tsx
  src/components/common/button/index.ts
  src/styles/theme.ts
  src/types/button.ts
Labels: feat, style

#12 [#9] 공통 dialog 컴포넌트 및 아이디어 개요 dialog
  package-lock.json
  package.json
  src/components/IbulDialog/IdeaOutline.tsx
  src/components/common/Dialog/Close.tsx
  src/components/common/Dialog/Content.tsx
  src/components/common/Dialog/Description.tsx
  src/components/common/Dialog/Overlay.tsx
  src/components/common/Dialog/Portal.tsx
  src/components/common/Dialog/Root.tsx
  src/components/common/Dialog/Title.tsx
  src/components/common/Dialog/Trigger.tsx
  src/components/common/Dialog/index.ts
  src/components/common/button/Button.tsx
  src/styles/theme.ts
  src/types/styled.d.ts
Labels: feat

#21 [#20] 아이디어 유형 선택 컴포넌트
  package-lock.json
  package.json
  src/components/IdeaTypeGroup.tsx
  src/components/common/ToggleGroup/Item.tsx
  src/components/common/ToggleGroup/Root.tsx
  src/components/common/ToggleGroup/index.ts
  src/constants/idea.ts
  src/store/.gitkeep
  src/store/atoms/idea.ts
  src/store/atoms/index.ts
  src/store/index.ts
Labels: feat

#25 [#24] 레이아웃 크기 수정
  src/components/IbulDialog/IdeaOutline.tsx
  src/components/Layout.tsx
  src/styles/theme.ts
Labels: fix

#27 [#26] storybook 세팅
  .gitignore
  .husky/pre-commit
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/common/Button.stories.ts
  src/stories/header.css
  src/stories/page.css
Labels: feat
